In [2]:
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences

In [3]:
# define documents
docs = ['Well done!',
'Good work',
'Great effort',
'nice work',
'Excellent!',
'Weak',
'Poor effort!',
'not good',
'poor work',
'Could have done better.']
# define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [6]:
# integer encode the documents
vocab_size = 100
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[25, 36], [67, 72], [82, 5], [47, 72], [25], [15], [80, 5], [71, 67], [80, 72], [33, 37, 36, 84]]


In [9]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[25 36  0  0]
 [67 72  0  0]
 [82  5  0  0]
 [47 72  0  0]
 [25  0  0  0]
 [15  0  0  0]
 [80  5  0  0]
 [71 67  0  0]
 [80 72  0  0]
 [33 37 36 84]]


In [58]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential

In [59]:
from tensorflow.keras import layers

In [60]:
# define the model
model = tf.keras.Sequential()
model.add(layers.Embedding(vocab_size, 8, input_length=max_length))
model.add(layers.Flatten())
model.add(layers.Dense(1, activation='sigmoid'))


In [61]:
import numpy as np
labels=np.array(labels)

In [63]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
model.summary()
# fit the model
model.fit(padded_docs, labels, epochs=100, verbose=2)


Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_2 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
Train on 10 samples
Epoch 1/100
10/10 - 1s - loss: 0.6319 - acc: 0.8000
Epoch 2/100
10/10 - 0s - loss: 0.6305 - acc: 0.8000
Epoch 3/100
10/10 - 0s - loss: 0.6291 - acc: 0.8000
Epoch 4/100
10/10 - 0s - loss: 0.6277 - acc: 0.8000
Epoch 5/100
10/10 - 0s - loss: 0.6263 - acc: 0.8000
Epoch 6/100
10/10 - 0s - loss: 0.6248 - acc: 0.8000
Epoch 7/100
10/10 - 0s - loss: 0.6234 - acc: 0.8000
E

In [64]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000
