## Import Library

In [1]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [21]:
file1 = open("MyFile.txt","a") 

# store its reference in the variable file1 
# and "MyFile2.txt" in D:\Text in file2 
file2 = open(r"D:\Text\MyFile2.txt","w+") 


FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Text\\MyFile2.txt'

In [1]:
#reading a text file in python
file1 = open('car.txt', 'r') # file handle
lines = file1.readlines() 

In [2]:
lines[4]

'The new Accord was also high on all kinds of tech and features oozing comfort and luxury on the inside. But it came at a price, the latest Accord was priced around 37 lakhs ex-showroom Delhi which stacked it right up with the German cars at that price point. The strong selling point of the Accord in India had always been providing luxury and performance at a price point much less than the German counterparts. But since that factor was no longer there, the new Accord bombed in the market. Frankly, no was willing to pay such a premium for a Honda. Soon this Accord was also discontinued in India with extremely few examples on the road.\n'

## Lowercase

In [21]:
text = "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife."
text = text.upper()
print(text)

IT IS A TRUTH UNIVERSALLY ACKNOWLEDGED, THAT A SINGLE MAN IN POSSESSION OF A GOOD FORTUNE, MUST BE IN WANT OF A WIFE.


In [18]:
lines[4].lower()  # to lower case

'the new accord was also high on all kinds of tech and features oozing comfort and luxury on the inside. but it came at a price, the latest accord was priced around 37 lakhs ex-showroom delhi which stacked it right up with the german cars at that price point. the strong selling point of the accord in india had always been providing luxury and performance at a price point much less than the german counterparts. but since that factor was no longer there, the new accord bombed in the market. frankly, no was willing to pay such a premium for a honda. soon this accord was also discontinued in india with extremely few examples on the road.\n'

In [19]:
lines[4].upper() # to upper case

'THE NEW ACCORD WAS ALSO HIGH ON ALL KINDS OF TECH AND FEATURES OOZING COMFORT AND LUXURY ON THE INSIDE. BUT IT CAME AT A PRICE, THE LATEST ACCORD WAS PRICED AROUND 37 LAKHS EX-SHOWROOM DELHI WHICH STACKED IT RIGHT UP WITH THE GERMAN CARS AT THAT PRICE POINT. THE STRONG SELLING POINT OF THE ACCORD IN INDIA HAD ALWAYS BEEN PROVIDING LUXURY AND PERFORMANCE AT A PRICE POINT MUCH LESS THAN THE GERMAN COUNTERPARTS. BUT SINCE THAT FACTOR WAS NO LONGER THERE, THE NEW ACCORD BOMBED IN THE MARKET. FRANKLY, NO WAS WILLING TO PAY SUCH A PREMIUM FOR A HONDA. SOON THIS ACCORD WAS ALSO DISCONTINUED IN INDIA WITH EXTREMELY FEW EXAMPLES ON THE ROAD.\n'

## Removing Punctuation

In [22]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [4]:
#list comprehension
text_p = "".join([char for char in text if char not in string.punctuation])
print(text_p)

it is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife


In [28]:
text

'IT IS A TRUTH UNIVERSALLY ACKNOWLEDGED, THAT A SINGLE MAN IN POSSESSION OF A GOOD FORTUNE, MUST BE IN WANT OF A WIFE.'

In [29]:
len(text)

117

In [36]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [44]:
text2=[]
for char in text:
    if  not char in string.punctuation:
        text2.append(char)
# split vs join:
text2=''.join(text2).lower()        
        
    

In [45]:
text2

'it is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife'

In [ ]:
#assignment  : try to  remove punctuation using regular expressions : re!!

In [ ]:
####################tokenization##############################:
#breaking down a raw string into constituent words/characters.
#various forms of tokenization : word tokenize,char tokenize,sentence level tokenization..

In [48]:
lines[4].split()  # tokenization

['The',
 'new',
 'Accord',
 'was',
 'also',
 'high',
 'on',
 'all',
 'kinds',
 'of',
 'tech',
 'and',
 'features',
 'oozing',
 'comfort',
 'and',
 'luxury',
 'on',
 'the',
 'inside.',
 'But',
 'it',
 'came',
 'at',
 'a',
 'price,',
 'the',
 'latest',
 'Accord',
 'was',
 'priced',
 'around',
 '37',
 'lakhs',
 'ex-showroom',
 'Delhi',
 'which',
 'stacked',
 'it',
 'right',
 'up',
 'with',
 'the',
 'German',
 'cars',
 'at',
 'that',
 'price',
 'point.',
 'The',
 'strong',
 'selling',
 'point',
 'of',
 'the',
 'Accord',
 'in',
 'India',
 'had',
 'always',
 'been',
 'providing',
 'luxury',
 'and',
 'performance',
 'at',
 'a',
 'price',
 'point',
 'much',
 'less',
 'than',
 'the',
 'German',
 'counterparts.',
 'But',
 'since',
 'that',
 'factor',
 'was',
 'no',
 'longer',
 'there,',
 'the',
 'new',
 'Accord',
 'bombed',
 'in',
 'the',
 'market.',
 'Frankly,',
 'no',
 'was',
 'willing',
 'to',
 'pay',
 'such',
 'a',
 'premium',
 'for',
 'a',
 'Honda.',
 'Soon',
 'this',
 'Accord',
 'was',
 'a

## Word Tokenization

In [49]:
from nltk import word_tokenize
words = word_tokenize(lines[4])
print(words)

['The', 'new', 'Accord', 'was', 'also', 'high', 'on', 'all', 'kinds', 'of', 'tech', 'and', 'features', 'oozing', 'comfort', 'and', 'luxury', 'on', 'the', 'inside', '.', 'But', 'it', 'came', 'at', 'a', 'price', ',', 'the', 'latest', 'Accord', 'was', 'priced', 'around', '37', 'lakhs', 'ex-showroom', 'Delhi', 'which', 'stacked', 'it', 'right', 'up', 'with', 'the', 'German', 'cars', 'at', 'that', 'price', 'point', '.', 'The', 'strong', 'selling', 'point', 'of', 'the', 'Accord', 'in', 'India', 'had', 'always', 'been', 'providing', 'luxury', 'and', 'performance', 'at', 'a', 'price', 'point', 'much', 'less', 'than', 'the', 'German', 'counterparts', '.', 'But', 'since', 'that', 'factor', 'was', 'no', 'longer', 'there', ',', 'the', 'new', 'Accord', 'bombed', 'in', 'the', 'market', '.', 'Frankly', ',', 'no', 'was', 'willing', 'to', 'pay', 'such', 'a', 'premium', 'for', 'a', 'Honda', '.', 'Soon', 'this', 'Accord', 'was', 'also', 'discontinued', 'in', 'India', 'with', 'extremely', 'few', 'examples

## Stopword Filtering

In [50]:
lines[4]

'The new Accord was also high on all kinds of tech and features oozing comfort and luxury on the inside. But it came at a price, the latest Accord was priced around 37 lakhs ex-showroom Delhi which stacked it right up with the German cars at that price point. The strong selling point of the Accord in India had always been providing luxury and performance at a price point much less than the German counterparts. But since that factor was no longer there, the new Accord bombed in the market. Frankly, no was willing to pay such a premium for a Honda. Soon this Accord was also discontinued in India with extremely few examples on the road.\n'

In [ ]:
 # important words : new accord high all kinds tech features oozing comfort inside

In [51]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [54]:
## list comprehension:###
list2=[1,2,3,4,5]

[x*x for x in list2]

[1, 4, 9, 16, 25]

In [58]:
pre_proc_text=[x for x in lines[4].split() if x not in stop_words]

In [61]:
' '.join(pre_proc_text)

'The new Accord also high kinds tech features oozing comfort luxury inside. But came price, latest Accord priced around 37 lakhs ex-showroom Delhi stacked right German cars price point. The strong selling point Accord India always providing luxury performance price point much less German counterparts. But since factor longer there, new Accord bombed market. Frankly, willing pay premium Honda. Soon Accord also discontinued India extremely examples road.'

In [7]:
filtered_words = [word for word in words if word not in stop_words]
print(filtered_words)

['truth', 'universally', 'acknowledged', 'single', 'man', 'possession', 'good', 'fortune', 'must', 'want', 'wife']


In [ ]:
                 ####################next session###############################

In [ ]:
stemming :
lemmatization : 

In [ ]:
root of a word : base form of any given word : 
        

In the areas of Natural Language Processing we come across situation where two or more words have a common root. For example, the three words - agreed, agreeing and agreeable have the same root word agree. A search involving any of these words should treat them as the same word which is the root word. So it becomes essential to link all the words into their root word. The NLTK library has methods to do this linking and give the output showing the root word.

In [ ]:
#stemming  :  reducing  a word to its root form. ex: agreed, agreeing and agreeable : --> agree

In [7]:
import nltk
from nltk.stem.porter import PorterStemmer
porter_stemmer = PorterStemmer()

word_data = "It originated from the idea that there are readers who prefer learning new skills from the comforts of their drawing rooms"
# First Word tokenization
nltk_tokens = nltk.word_tokenize(word_data)


In [11]:
#Next find the roots of the word
stem_words=[]
for word in nltk_tokens:
    print( "Actual: %s  Stem: %s"  % (word,porter_stemmer.stem(word)))
    stem_words.append(porter_stemmer.stem(word))

Actual: It  Stem: It
Actual: originated  Stem: origin
Actual: from  Stem: from
Actual: the  Stem: the
Actual: idea  Stem: idea
Actual: that  Stem: that
Actual: there  Stem: there
Actual: are  Stem: are
Actual: readers  Stem: reader
Actual: who  Stem: who
Actual: prefer  Stem: prefer
Actual: learning  Stem: learn
Actual: new  Stem: new
Actual: skills  Stem: skill
Actual: from  Stem: from
Actual: the  Stem: the
Actual: comforts  Stem: comfort
Actual: of  Stem: of
Actual: their  Stem: their
Actual: drawing  Stem: draw
Actual: rooms  Stem: room


In [15]:
str_stem = ' '.join(stem_words)

In [17]:
word_data

'It originated from the idea that there are readers who prefer learning new skills from the comforts of their drawing rooms'

In [16]:
str_stem

'It origin from the idea that there are reader who prefer learn new skill from the comfort of their draw room'

Lemmatization is similar to stemming but it brings context to the words.So it goes a steps further by linking words with similar meaning to one word. For example if a paragraph has words like cars, trains and automobile, then it will link all of them to automobile. In the below program we use the WordNet lexical database for lemmatization.

In [ ]:
#examples of lemmatization
#joy,happiness--> happy
#sadness, sad,grief--> sad

In [18]:
 nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Shruthi S
[nltk_data]     D\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [20]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

word_data = " joy happy sad grief It originated from the idea that there are readers who prefer learning new skills from the comforts of their drawing rooms"
nltk_tokens = nltk.word_tokenize(word_data)
for word in nltk_tokens:
       print ("Actual: %s  Lemma: %s"  % (word,wordnet_lemmatizer.lemmatize(word)))

Actual: joy  Lemma: joy
Actual: happy  Lemma: happy
Actual: sad  Lemma: sad
Actual: grief  Lemma: grief
Actual: It  Lemma: It
Actual: originated  Lemma: originated
Actual: from  Lemma: from
Actual: the  Lemma: the
Actual: idea  Lemma: idea
Actual: that  Lemma: that
Actual: there  Lemma: there
Actual: are  Lemma: are
Actual: readers  Lemma: reader
Actual: who  Lemma: who
Actual: prefer  Lemma: prefer
Actual: learning  Lemma: learning
Actual: new  Lemma: new
Actual: skills  Lemma: skill
Actual: from  Lemma: from
Actual: the  Lemma: the
Actual: comforts  Lemma: comfort
Actual: of  Lemma: of
Actual: their  Lemma: their
Actual: drawing  Lemma: drawing
Actual: rooms  Lemma: room


In [25]:
#vectorization : converting tokenized,cleaned text into meaning numeric repreentations.


In [ ]:
# one hot encoding
# count vectorizer
# tfidf vectorizer
#bag of words model 

# one hot encoding

Suppose we have a sentence as “Can I eat the Pizza”.
looking at this, we can directly say that all the words are different from each other but how will the machine know?
so when we try to apply one hot ending i.e converting the categories into numerical labels.
Firstly, convert the text to lower and then sort the words in ascending form i.e A-Z.
Now we’ll have “can, eat, i, pizza, the”.
Give a numerical label as we can see can is at 0th position and eat is at 1 same way, assign the values like can:0, i:2, eat:1, the:4, pizza:3.
Transform to binary vectors.


In [ ]:
can(0) i(2) eat(1) the(4) pizza(3) # converting to lower case
can eat i pizza the # sorting in ascending order.




In [ ]:
index(can)-->0
index(eat)-->1
index(i)-->2
index(pizza)-->3
index(the) -->4

In [ ]:
[[1. 0. 0. 0. 0.] #can
 [0. 0. 1. 0. 0.] #i
 [0. 1. 0. 0. 0.] #eat
 [0. 0. 0. 0. 1.] #the
 [0. 0. 0. 1. 0.]] #pizza

In [ ]:
actual line ='can i eat the pizza'

In [ ]:
can     eat      i       pizza      the 
0       1        2         3         4


1       0         0         0         0   -> can
0       0         1         0         0   --> i
0       1         0         0         0   -->eat
0       0         0         0         1  -->the
0       0         0         1         0  --> pizza



In [ ]:
(5,5)  # one hot  encoding : 

In [ ]:
onehot_encoder = OneHotEncoder(sparse=False)

In [26]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
#define example


In [29]:
in_str=' '.join(data)

In [30]:
in_str

'cold cold warm cold hot hot warm cold warm hot'

In [45]:
data=in_str.split()

In [46]:
data

['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']

In [47]:
le=LabelEncoder()
data=le.fit_transform(data)

In [48]:
data

array([0, 0, 2, 0, 1, 1, 2, 0, 2, 1], dtype=int64)

In [49]:
data.shape

(10,)

In [50]:
#when working with 1D array as input in sklearn-->  convert into  2D
data=data.reshape(-1,1)

In [51]:
data.shape

(10, 1)

In [53]:
ohe=OneHotEncoder()
vect_data=ohe.fit_transform(data)

In [54]:
type(vect_data)  # csr ??

scipy.sparse.csr.csr_matrix

In [57]:
in_str  # --> matrix of shape(10,3)--> total 10 words and 3 unique words

'cold cold warm cold hot hot warm cold warm hot'

In [55]:
vect_data.toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
################################################

In [58]:
#29th oct-- > count vectorizer , tfidf vectorizer, naive bayes algorithm implementation
#30th oct--> support vector machines(SVM)

In [1]:
from sklearn.feature_extraction.text import CountVectorizer 

document = ["One Geek helps Two Geeks", 
			"Two Geeks help Four Geeks", 
			"Each Geek helps many other Geeks at GeeksforGeeks"] 



In [2]:
temp=[x.split() for x in document]

In [3]:
temp

[['One', 'Geek', 'helps', 'Two', 'Geeks'],
 ['Two', 'Geeks', 'help', 'Four', 'Geeks'],
 ['Each', 'Geek', 'helps', 'many', 'other', 'Geeks', 'at', 'GeeksforGeeks']]

In [11]:
xx=[]
for li in temp:
    for it in li:
        xx.append(it)
   

In [14]:
len(set(xx))

12

In [16]:
from sklearn.feature_extraction.text import CountVectorizer 

document = ["One Geek helps Two Geeks", 
			"Two Geeks help Four Geeks", 
			"Each Geek helps many other Geeks at GeeksforGeeks"] 

# Create a Vectorizer Object 
vectorizer = CountVectorizer() 

vector=vectorizer.fit_transform(document) 

# Printing the identified Unique words along with their indices 
print("Vocabulary: ", vectorizer.vocabulary_) 

# Summarizing the Encoded Texts 
print("Encoded Document is:") 
print(vector.toarray())


Vocabulary:  {'one': 9, 'geek': 3, 'helps': 7, 'two': 11, 'geeks': 4, 'help': 6, 'four': 2, 'each': 1, 'many': 8, 'other': 10, 'at': 0, 'geeksforgeeks': 5}
Encoded Document is:
[[0 0 0 1 1 0 0 1 0 1 0 1]
 [0 0 1 0 2 0 1 0 0 0 0 1]
 [1 1 0 1 1 1 0 1 1 0 1 0]]


In [20]:
corpus=lines[4]

In [ ]:
# draw back of count vect  and one hot : common words(and ,the ,on) are given equal importance as rare words:

In [ ]:
#TF-IDF vectorizer : term frequency - inverse document frequency 

In [25]:
corpus=corpus.split(".")

In [26]:
len(corpus)

7

In [35]:
corpus[1]

' But it came at a price, the latest Accord was priced around 37 lakhs ex-showroom Delhi which stacked it right up with the German cars at that price point'

In [ ]:
at  : tf + idf  = 3 +
accord  : tf + idf  =1 +

In [ ]:
tf('term')  :  term frequency : freq of the 'term' in that document.
        

In [ ]:
df('term')  :  the number of documents in the corpus that contain the 'term'
idf('term') : number of documents in the corpus /df('term')

In [ ]:
corpus -- >100 documents


In [ ]:
document 1 : the word 'the' appears-- >50 times and 'golden'  appears once. len(document 1)-->150
tf('the')--> 50
tf('golden')--> 1
normalized tf('the')-- > 50/150
normalized tf('golden') -- > 1/150

In [ ]:
df('the')=75
df('golden')=5
idf('the') = 100/75=1  log(1.33  = 0.41
idf('golden')  =100/5 =20  log(20) = 4.32

In [ ]:
tf-idf('term') = tf('term')* idf('term')  # final formula for tf-idf

In [ ]:
tf-idf('the')=  50*0.41 = 20.5  
tf-idf('golden') = 5*4.32 = 24 

In [ ]:
#

## Stemming

## POS

In [9]:
from nltk import pos_tag
pos = pos_tag(filtered_words)
print(pos)

[('truth', 'NN'), ('universally', 'RB'), ('acknowledged', 'VBD'), ('single', 'JJ'), ('man', 'NN'), ('possession', 'NN'), ('good', 'JJ'), ('fortune', 'NN'), ('must', 'MD'), ('want', 'VB'), ('wife', 'NN')]
